# Palm rejection for the Asahi MTP trackpad (#100).
#
# libinput's shipped [Apple Laptop Touchpad (MTP)] sets AttrSizeHint=104x75, a
# 13-inch pad. 14" and 16" Apple Silicon pads report their real size via udev
# (a 16-inch M2 Max is 157x96 mm). The undersized hint makes palm detection
# map onto the wrong physical area, so resting palms while typing move the
# cursor and click.
#
# /etc/libinput is read after /usr/share/libinput, so this override wins.
# AttrSizeHint cannot be unset, only replaced, which is why the hint is
# measured from the device rather than copied from the 13-inch default.

quirks_dir="${OMARCHY_LIBINPUT_QUIRKS_DIR:-/etc/libinput}"
input_root="${OMARCHY_INPUT_SYSFS:-/sys/class/input}"
compatible="${OMARCHY_APPLE_COMPATIBLE:-/proc/device-tree/compatible}"
arch="${OMARCHY_TEST_ARCH:-$(uname -m)}"

if [[ $arch == "aarch64" && -f $compatible ]] && grep -Faiq 'apple,' "$compatible"; then
  width=${OMARCHY_APPLE_MTP_WIDTH_MM:-}
  height=${OMARCHY_APPLE_MTP_HEIGHT_MM:-}

  if [[ -z $width || -z $height ]]; then
    # WIDTH_MM lives on the event node (eventN), not the parent inputN.
    for namefile in "$input_root"/event*/device/name; do
      [[ -r $namefile ]] || continue
      [[ $(<"$namefile") == "Apple MTP multi-touch" ]] || continue
      event=$(dirname "$(dirname "$namefile")")
      if command -v udevadm >/dev/null; then
        while IFS='=' read -r key value; do
          case $key in
            ID_INPUT_WIDTH_MM) width=$value ;;
            ID_INPUT_HEIGHT_MM) height=$value ;;
          esac
        done < <(udevadm info -q property -p "$event" 2>/dev/null || true)
      fi
      break
    done
  fi

  mkdir -p "$quirks_dir"
  {
    cat <<'EOF'
# Generated by install/hardware/apple/fix-mtp-trackpad.sh.
# Do not add MatchVendor: Asahi platform devices often have no ID_VENDOR.

[Apple Laptop Keyboard (MTP)]
MatchUdevType=keyboard
MatchName=Apple MTP keyboard
AttrKeyboardIntegration=internal

[Apple Laptop Touchpad (MTP)]
MatchUdevType=touchpad
MatchName=Apple MTP multi-touch
ModelAppleTouchpad=1
AttrTouchSizeRange=150:130
AttrPalmSizeThreshold=1600
EOF
    if [[ $width =~ ^[0-9]+$ && $height =~ ^[0-9]+$ ]]; then
      printf 'AttrSizeHint=%sx%s\n' "$width" "$height"
    fi
  } >"$quirks_dir/omarchy-apple-mtp.quirks"
fi
