# Apple Silicon Touch Bar: tiny-dfr already paints the DSI strip. Ship an
# Omarchy-flavoured layout (menu, terminal, lock, screenshot, media) as the
# default media layer so Fn is not required for the useful keys.
# T2 Macs are x86_64 and keep the kernel Boot Camp Touch Bar; do not install
# tiny-dfr there.

compatible="${OMARCHY_APPLE_COMPATIBLE:-/proc/device-tree/compatible}"
conf_src="$OMARCHY_PATH/default/tiny-dfr/config.toml"
conf_dst="${OMARCHY_TINY_DFR_CONF:-/etc/tiny-dfr/config.toml}"

[[ $(uname -m) == "aarch64" ]] || return 0
[[ -f $compatible ]] && grep -Faiq 'apple,' "$compatible" || return 0
[[ -f $conf_src ]] || return 0

echo "Configuring the Apple Silicon Touch Bar"

if omarchy-pkg-missing tiny-dfr; then
  omarchy-pkg-add tiny-dfr ||
    echo "Warning: tiny-dfr could not be installed; the Touch Bar stays on firmware defaults."
fi

if [[ -f $conf_dst ]] &&
  ! grep -q 'Omarchy Apple Silicon Touch Bar' "$conf_dst" &&
  ! grep -q 'Generated by omarchy.touchbar' "$conf_dst"; then
  echo "Leaving $conf_dst in place (not an Omarchy Touch Bar config)"
  return 0
fi

sudo mkdir -p "$(dirname "$conf_dst")"
sudo install -m 644 "$conf_src" "$conf_dst"

if command -v systemctl >/dev/null; then
  sudo systemctl restart tiny-dfr.service 2>/dev/null || true
fi
