#!/bin/bash
# Render a Touch Bar layout JSON into tiny-dfr config.toml.
# Default layout is this plugin's layout.json. A user overlay at
# ~/.config/omarchy/touchbar.json wins when present.

set -euo pipefail

PLUGIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
USER_LAYOUT="${OMARCHY_TOUCHBAR_LAYOUT:-$HOME/.config/omarchy/touchbar.json}"
STOCK_LAYOUT="$PLUGIN_DIR/layout.json"
ETC_CONF="${OMARCHY_TOUCHBAR_ETC:-/etc/tiny-dfr/config.toml}"

if [[ -f $USER_LAYOUT ]]; then
  LAYOUT=$USER_LAYOUT
else
  LAYOUT=$STOCK_LAYOUT
fi

[[ -f $LAYOUT ]] || exit 0
command -v python3 >/dev/null || exit 0

generated=$(python3 - "$LAYOUT" <<'PY'
import json, os, sys

layout = json.loads(open(sys.argv[1]).read())

def toml_btn(btn):
    key = btn.get("key")
    if isinstance(key, list):
        action = "[" + ", ".join(f'"{k}"' for k in key) + "]"
    else:
        action = f'"{key}"'
    parts = [f"Action = {action}"]
    if btn.get("icon"):
        parts.insert(0, f'Icon = "{btn["icon"]}"')
    elif btn.get("text"):
        parts.insert(0, f'Text = "{btn["text"]}"')
    if btn.get("stretch"):
        parts.append(f"Stretch = {int(btn['stretch'])}")
    return "    { " + ", ".join(parts) + " }"

def layer(name, buttons):
    rows = ",\n".join(toml_btn(b) for b in buttons if b.get("key"))
    return f"{name} = [\n{rows}\n]\n"

media = layout.get("buttons") or []
fn = layout.get("fnLayer") or []
media_default = "true" if layout.get("mediaLayerDefault", True) else "false"
outlines = "true" if layout.get("showButtonOutlines", True) else "false"
adaptive = "true" if layout.get("adaptiveBrightness", True) else "false"

print(f"""# Generated by omarchy.touchbar from {os.path.basename(sys.argv[1])}.
MediaLayerDefault = {media_default}
ShowButtonOutlines = {outlines}
EnablePixelShift = false
FontTemplate = ":bold"
AdaptiveBrightness = {adaptive}
ActiveBrightness = 128

{layer("PrimaryLayerKeys", fn)}
{layer("MediaLayerKeys", media)}
""")
PY
)

toml_out=${OMARCHY_TOUCHBAR_TOML:-/tmp/omarchy-touchbar.toml}
printf '%s' "$generated" >"$toml_out"
printf '%s\n' "$toml_out"

[[ ${OMARCHY_TOUCHBAR_SKIP_INSTALL:-} == 1 ]] && exit 0

if [[ -f $ETC_CONF ]] && cmp -s "$toml_out" "$ETC_CONF"; then
  exit 0
fi

sudo mkdir -p "$(dirname "$ETC_CONF")"
sudo install -m 644 "$toml_out" "$ETC_CONF"
if command -v systemctl >/dev/null; then
  sudo systemctl restart tiny-dfr.service 2>/dev/null || true
fi
